### ISSUE TITLE
Offline problem

### ISSUE THREAD

**Issue by Bulbaterson** [mkko120/woominecraft-wp-unlocked#1]
Nie działa wsparcie dla kont offline.

**Comment by mkko120** [comment]
Co masz na mysli mowiac nie dziala? Jakies bledy? Szczegoly?

============================

What do you mean it doesn't work? Any errors? More details?

**Comment by Bulbaterson** [comment]
"We cannot retrieve your account from the Mojang API. Try again later, or contact an administrator."
Taki bład przy wpisaniu dowolnego nicku wyskakuje przy finalizacji
Jakbyś mógł to najlepeij prosze o kontakt na discordzie Bulbaterson#8048
Ps. Jestem Polakiem

**Comment by mkko120** [comment]
Zalatwione na pv i przez [c8e6577](https://github.com/mkko120/woominecraft-wp-unlocked/commit/c8e65772a5988b2ea9689225a169806cf7952a5a)
